import { buf } from 'crc-32';
import { timingSafeEqual } from 'crypto';
import { InvalidTokenError } from '../error';
import type { Validator } from './validator';
import type { Encoder } from '../encoder';

// Base62-encoded CRC32 (4 bytes) is at most 6 characters
const CHECKSUM_LENGTH = 6;

function calculateCrc32LE(val: Uint8Array): Buffer {
    const crc32 = Buffer.allocUnsafe(4);
    crc32.writeInt32LE(buf(val));
    return crc32;
}

function calculateCrc32BE(val: Uint8Array): Buffer {
    const crc32 = Buffer.allocUnsafe(4);
    crc32.writeUInt32BE(buf(val) >>> 0);
    return crc32;
}

/**
 * CRC32 validator that operates on base62-encoded token bodies.
 *
 * New format (GitHub-compatible): CRC32 is computed over the encoded payload
 * string as big-endian, then base62-encoded and padded to 6 characters.
 *
 * Also supports verifying old-format tokens where CRC32 was computed over raw
 * bytes as little-endian and concatenated before encoding. This fallback is
 * best-effort migration behaviour for tokens generated by earlier versions.
 */
export class Crc32Validator implements Validator {
    private readonly encoder: Encoder;

    constructor(encoder: Encoder) {
        this.encoder = encoder;
    }

    append(encoded: string): string {
        const crcBytes = calculateCrc32BE(Buffer.from(encoded));
        const encodedCrc = this.encoder.encode(crcBytes);
        if (encodedCrc.length > CHECKSUM_LENGTH) {
            throw new Error(`Encoder produced ${encodedCrc.length}-char checksum, expected at most ${CHECKSUM_LENGTH}. Use a base62 or compatible encoder.`);
        }
        return encoded + encodedCrc.padStart(CHECKSUM_LENGTH, '0');
    }

    verify(encoded: string): string {
        if (encoded.length < CHECKSUM_LENGTH + 1) {
            throw new InvalidTokenError('Token body too short');
        }
        const payload = encoded.slice(0, -CHECKSUM_LENGTH);
        const checksum = encoded.slice(-CHECKSUM_LENGTH);
        const crcBytes = calculateCrc32BE(Buffer.from(payload));
        const expectedChecksum = this.encoder.encode(crcBytes).padStart(CHECKSUM_LENGTH, '0');
        if (timingSafeEqual(Buffer.from(checksum), Buffer.from(expectedChecksum))) {
            return payload;
        }
        // Fallback: try old format (CRC32 LE on raw bytes, encoded together)
        return this.verifyOldFormat(encoded);
    }

    private verifyOldFormat(encoded: string): string {
        const decoded = this.encoder.decode(encoded);
        if (decoded.length < 5) {
            throw new InvalidTokenError('Token body too short');
        }
        const data = decoded.subarray(0, -4);
        const crc = decoded.subarray(-4);
        if (!timingSafeEqual(crc, calculateCrc32LE(data))) {
            throw new InvalidTokenError('Invalid CRC32 check value');
        }
        return this.encoder.encode(data);
    }
}
